function getRandomGreeting() {
  var greetings = [
    "Bubber is the goat",
    "OhMyGodASnake!",
    "New Look, Same great taste!",
    "jablicky asparagus timmypop",
    "How many sides does a circle have?",
    "You can read btw",
    "Made you look!",
    "Redbull gives you wings...",
    "Since 2020!",
    "As seen on TV!",
    "guess what! vvmvvh",
    "Cold as ice!",
    "Made in the US!",
    "Made by Bubber!",
    "Reload the page NOW!",
    "Please don't jump on the pixels",
    "Running IKEA.exe",
    "WARNING: You may lose your pocket chimp if you proceed!",
    "Do you bite your ice cream?",
    "#Relatable",
    "You got bees on your phone?",
    "Powered by hamsters!",
    "*insert cool explosion*",
    "Gotta go fast!",
    "My iPad passcode is 93353 btw",
    "james the popsicle?!",
    "Sponsored by RAID SHADOW LEGENDS",
    "Sponsored by Chimp & co!",
    "la pa",
    "Powered by Frank the laptop!",
    "the terminal velocity of a baby is 43 MPH",
    "Everlong",
    "I'm gonna pop some gizzies",
    "Shoutout to my cat.",
    "thx stackoverflow!",
    "are you a gamer?",
    "It is time to get funky!",
    "I SWEAR TO GOD I DID NOT LIGHT JOHNS HOUSE ON FIRE.",
    "Don't ask questions if you can't handle the answers!",
    "If you are using Microsoft Edge, you need some help.",
    "Vengeance is hereby mine",
    "Shoutout to Schlopis!",
    "Shoutout to PRG!",
    "Low price, high scores.",
    "do mice like it when i laa.",
    "Is this the United Airlines costumer service center?",
    "bottom text",
    "buzzy bee disposal center",
    "No fun allowed",
    "dude. GRAGGLE.",
    "i do love buying pringle guzzies",
    "no matter what you say I DONT HAVE HORSES",
    "WHERES MY V-BUCKS MOM >:(",
    "Your browser's favorite Allen key.",
    "reload for another message",
    "hi graggle",
    "i just splatooned on my dog!",
    "And just to think I knew him before he was famous",
    "Trust me, I did not copy Minecraft with this",
    "It is everyday bro",
    "Everything fits in the Kallax",
    "This is the 5th time this week, and it's only Monday",
    "You bum",
    "Designed for your browser, built for your break.",
    "Don't get lost in the showroom.",
    "Drift Boss is pretty fun",
    "Flat-packed fun, no assembly required.",
    "The skeleton with the sword. HE FOUND YOU!",
    "I spent too much time making these",
    "Your home for unblocked essentials.",
   ];
    var randomIndex = Math.floor(Math.random() * greetings.length);
    return greetings[randomIndex];
}

document.getElementById("subtitle").innerText = getRandomGreeting();
